# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = 'https://pokemontt-arena.netlify.app'
    Access-Control-Allow-Credentials = 'true'
    Access-Control-Allow-Headers = 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With, Origin'